### PR TITLE
 Add poweron architecture ppc64le to travis build

### PR DESCRIPTION
**Pull request by asellappen**
Add poweron architecture ppc64le to travis build and chnaged on travis.yml.

### CODE REVIEW

**Comment by asellappen** [comment]
Pls help to review the change for poweron.
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

**Comment by wbond** [comment]
Please remove the comment “power on” and sort the addition so it is below the other Python 2.7 config.

**Comment by asellappen** [comment]
Thanks for review and feedback, I have applied the changes as you expected .Please review now

**Comment by wbond** [comment]
You've moved around the PyPy implementation, making the diff more confusing. I'm just going to commit on master.

**Pull request closed without merging**
