### PR TITLE
Add support for rfc2633 sMIME capabilities signed attr

### PR DESCRIPTION
**Pull request by Hellzed**
Hi,
I'm using asn1crypto on a project that requires support for S/MIME Version 3 (rfc2633), especially the [sMIME capabilities](https://datatracker.ietf.org/doc/html/rfc2633#section-2.5.2) signed attribute.
Right now, asn1crypto master only parses the sMIME capabilities signed attr into universal types (a set of sequences) with raw OIDs.

This also exposes some (probably buggy) behaviour from asn1crypto, where unknown signed attrs such as sMIME capabilities are empty and hoisted at the beginning of the signed attrs field when dumping.
For an example, see this PKCS#7 signature [before](https://lapo.it/asn1js/#MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwEAAKCAMIIHRzCCBfugAwIBAgIQJ4WRzTUUujDwpbBFw_3ZATBBBgkqhkiG9w0BAQowNKAPMA0GCWCGSAFlAwQCAQUAoRwwGgYJKoZIhvcNAQEIMA0GCWCGSAFlAwQCAQUAogMCASAwdTELMAkGA1UEBhMCREUxJTAjBgNVBAoTHFQtU3lzdGVtcyBJbnRlcm5hdGlvbmFsIEdtYkgxHzAdBgNVBAsTFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxHjAcBgNVBAMTFVRlbGVTZWMgQnVzaW5lc3MgQ0EgMTAeFw0yMDAyMDcxMzM0MDlaFw0yMzAyMDcyMzU5NTlaMIHIMQswCQYDVQQGEwJERTEVMBMGA1UEChMMQW1wcmlvbiBHbWJIMRcwFQYDVQQLEw52My5hbXByaW9uLm5ldDEZMBcGA1UECwwQUlNBU1NBLVBTU19TTUlNRTEbMBkGA1UEAxMSR1JQOlNydkV4Y05ld2FzSUlQMRswGQYDVQQEExJHUlA6U3J2RXhjTmV3YXNJSVAxITAfBgkqhkiG9w0BCQEWEmVkaS5ibUBhbXByaW9uLm5ldDERMA8GA1UEBRMIMjAyMDAyMDcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCWwiay08N3c2EiF8tORbAz68z3Qh1Sw12RA0JF9kt6pQKppxFSL9ZmfusoQdy9LnPjryi8V2021CtySf6p_55FZi5ohh-yZWJXizcQp704f5RG9UqmKvg5JRuk5L81mO6SljSrjoMMEL1Ee0SVz-HvwShS0vQVJky5O23-7RpYb6LCvPM0aQUO0YncPsYLYOA9c3QbK2jje02rXPPkD9UTc8ODfjVc5tAYmuVg1dRn59IurXqDTmzxul6GbX_UYP2qIiEzRzSaOWRIThbKU3SxiZz-THIqOMK3GH66PDovbjcDai-_EQKnQxfdSDB4StAl4U54mosrKLjwXVU0ZTq3AgMBAAGjggMVMIIDETAfBgNVHSMEGDAWgBSGiJMfi-tVlmXVRwG9N4x8zajHozAdBgNVHQ4EFgQUQNwsdmIH3ePn1CJ0tAbxv1qY3rowDgYDVR0PAQH_BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDBYBgNVHSAEUTBPMEMGCSsGAQQBvUcNGTA2MDQGCCsGAQUFBwIBFihodHRwOi8vc2JjYS50ZWxlc2VjLmRlL2Rvd25sb2FkL2NwczIucGRmMAgGBgQAj3oBATAJBgNVHRMEAjAAMIHwBgNVHR8EgegwgeUwPaA7oDmGN2h0dHA6Ly9jcmwuc2JjYS50ZWxlc2VjLmRlL3JsL1RlbGVTZWNfQnVzaW5lc3NfQ0FfMS5jcmwwgaOggaCggZ2GgZpsZGFwOi8vbGRhcC5zYmNhLnRlbGVzZWMuZGUvQ049VGVsZVNlYyUyMEJ1c2luZXNzJTIwQ0ElMjAxLE9VPVQtU3lzdGVtcyUyMFRydXN0JTIwQ2VudGVyLE89VC1TeXN0ZW1zJTIwSW50ZXJuYXRpb25hbCUyMEdtYkgsQz1ERT9DZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0MIIBJwYIKwYBBQUHAQEEggEZMIIBFTAvBggrBgEFBQcwAYYjaHR0cDovL29jc3AwMy5zYmNhLnRlbGVzZWMuZGUvb2NzcHIwRAYIKwYBBQUHMAKGOGh0dHA6Ly9jcnQuc2JjYS50ZWxlc2VjLmRlL2NydC9UZWxlU2VjX0J1c2luZXNzX0NBXzEuY3J0MIGbBggrBgEFBQcwAoaBjmxkYXA6Ly9sZGFwLnNiY2EudGVsZXNlYy5kZS9jbj1UZWxlU2VjJTIwQnVzaW5lc3MlMjBDQSUyMDEsb3U9VC1TeXN0ZW1zJTIwVHJ1c3QlMjBDZW50ZXIsbz1ULVN5c3RlbXMlMjBJbnRlcm5hdGlvbmFsJTIwR21iSCxjPWRlP2NBQ2VydGlmaWNhdGUwHQYDVR0RBBYwFIESZWRpLmJtQGFtcHJpb24ubmV0MEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIAOCAQEAjlf8d-MqEbXDfpL9cZHZ927LXOBh_p48CtG7IhJNztHkAr__7o-wnk7uZRGoRpod6ODdDDvvNh7ysooO-AlEy-0XYdjJpbf8qEsf9Yr-Qyh42Xsi0YVLtRrCf_azIGmOfahycetlzCiTmufss1eD0x7madckNXNUg5kDGGkFY6a9LpN_TXbhr5kcMDKLoQBmkxcG_UfIL3ZzTTzo3f256wrcXHLvAGsTceZ61c793ulLTZH0PKDzQblvU8iFtA5PNuPJHnjpMptWtK2MTu_4hqKVf0IA9eftztzgS9KwV8CW4zG7eCC4rP2SASC3ceyflhq8Sb4R8i0fKCbtDTLTsjCCBXAwggRYoAMCAQICBkiNAl3W9DANBgkqhkiG9w0BAQsFADCBgjELMAkGA1UEBhMCREUxKzApBgNVBAoMIlQtU3lzdGVtcyBFbnRlcnByaXNlIFNlcnZpY2VzIEdtYkgxHzAdBgNVBAsMFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxJTAjBgNVBAMMHFQtVGVsZVNlYyBHbG9iYWxSb290IENsYXNzIDIwHhcNMTIxMTI5MTEyMzU1WhcNMjQxMTI5MjM1OTU5WjB1MQswCQYDVQQGEwJERTElMCMGA1UEChMcVC1TeXN0ZW1zIEludGVybmF0aW9uYWwgR21iSDEfMB0GA1UECxMWVC1TeXN0ZW1zIFRydXN0IENlbnRlcjEeMBwGA1UEAxMVVGVsZVNlYyBCdXNpbmVzcyBDQSAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0TDUTUTD5EtatBieDlEntaliSXoaBsBzLBGJVZKsDsv-SC-7XeP0qYi6gWvk-zcdLFfrRZhVQUaJx-enMWR7nngIn8AYP-lKYrGE_ODQzK2VLruAavWnZMU3-94956DNsaJ0NaPP7-1NdG26jSQatJ_8WlVGO__3wvF5enZ3z0_ryiKNdtgFmfcE8TyffNuoafBV36NBqElLbl0gcQ26iwluayLwpJ3zVonA1sBYMAhX5mLdjj_QveO6OFdfrdI1Ururrsa2nyESk69Fi1Y21cykTDYvM-G0guZkRV3u6tfcoE1Bf95mmYr9XW7sRet04gkT9orqqGcoak6f-BKstQIDAQABo4IB9jCCAfIwDgYDVR0PAQH_BAQDAgEGMB0GA1UdDgQWBBSGiJMfi-tVlmXVRwG9N4x8zajHozAfBgNVHSMEGDAWgBS_WSA2AHmgoCJrjNXyYdK4LMuCSjASBgNVHRMBAf8ECDAGAQH_AgEAMFMGA1UdIARMMEowPgYJKwYBBAG9Rw0ZMDEwLwYIKwYBBQUHAgEWI2h0dHA6Ly9zYmNhLnRlbGVzZWMuZGUvY3BzL2NwczIucGRmMAgGBmeBDAECAjCB-gYDVR0fBIHyMIHvMDqgOKA2hjRodHRwOi8vY3JsLnNiY2EudGVsZXNlYy5kZS9ybC9HbG9iYWxSb290X0NsYXNzXzIuY3JsMIGwoIGtoIGqhoGnbGRhcDovL2xkYXAuc2JjYS50ZWxlc2VjLmRlL0NOPVQtVGVsZVNlYyUyMEdsb2JhbFJvb3QlMjBDbGFzcyUyMDIsT1U9VC1TeXN0ZW1zJTIwVHJ1c3QlMjBDZW50ZXIsTz1ULVN5c3RlbXMlMjBFbnRlcnByaXNlJTIwU2VydmljZXMlMjBHbWJILEM9REU_QXV0aG9yaXR5UmV2b2NhdGlvbkxpc3QwOgYIKwYBBQUHAQEELjAsMCoGCCsGAQUFBzABhh5odHRwOi8vb2NzcDA0LnRlbGVzZWMuZGUvb2NzcHIwDQYJKoZIhvcNAQELBQADggEBAJOF0euEehlZyCWAOiSluZZxBpv-1g504EDd1c1dHSCAGUNJD3h23iPeXMw37aPKfEohBNklkZmxPweyZELcFOelj9PtrSBteR1SLBeyktCzXzAvRD5W7zRXtoeQqbxHdYgykz7vaUsaSjANsecNQwFlh3w3j5tK1atRyfb1l8MeP14UlK62DXJZ_OXXF1_E4mZO2maNKNEK1zu2LFqiTtbY75KVLWWZJGgwioINYs7fh__8OPWEes7HjHFGeiMpfaz2VigCrICLr1egSB2IYZ9KPv_fvKFmnRoBhvMcEVXLWtL8MLkU1isJB-xq4_aNURpEKUdul47BMdY1CPgeJE8wggPDMIICq6ADAgECAgEBMA0GCSqGSIb3DQEBCwUAMIGCMQswCQYDVQQGEwJERTErMCkGA1UECgwiVC1TeXN0ZW1zIEVudGVycHJpc2UgU2VydmljZXMgR21iSDEfMB0GA1UECwwWVC1TeXN0ZW1zIFRydXN0IENlbnRlcjElMCMGA1UEAwwcVC1UZWxlU2VjIEdsb2JhbFJvb3QgQ2xhc3MgMjAeFw0wODEwMDExMDQwMTRaFw0zMzEwMDEyMzU5NTlaMIGCMQswCQYDVQQGEwJERTErMCkGA1UECgwiVC1TeXN0ZW1zIEVudGVycHJpc2UgU2VydmljZXMgR21iSDEfMB0GA1UECwwWVC1TeXN0ZW1zIFRydXN0IENlbnRlcjElMCMGA1UEAwwcVC1UZWxlU2VjIEdsb2JhbFJvb3QgQ2xhc3MgMjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKpf2htf6HOR5dpc9KLmR-XzaFVgBR0CpLObWfMeiq80rfwNwtlIGe5pj8kg_CGqBxntsFysZcdf7QJ8e3wtG9a6uYDCGIIWhPpmsAjGVCOB5M25ST_2T243SCg4D8W-52hw_TmXTdLHmJFQqsREsyN9OUfpUmLWEpNetzGWQgX7dqceo_XC_Ol6xWypcU_qy3i8YK_H3vTZy75-M6VulIPwNPohq-qOcqA_pN4wW--GTWqVW0NEqBAVHOUBV8WY8eYGKJGqIMW3UyZRQ7ILEZVY4cAPdtnAjXyB83Jwnm_-Go7ZXzXGsm80fL5IT-JaOdfYnXien4Y-A14Zi0Si1ccCAwEAAaNCMEAwDwYDVR0TAQH_BAUwAwEB_zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFL9ZIDYAeaCgImuM1fJh0rgsy4JKMA0GCSqGSIb3DQEBCwUAA4IBAQAxA6JhCx906HI2xm35TZ76IqjhgVbPzbuf6quRGTivqnwVTfO2o42l9I72RKmn6CGVrT4AYhaI8AK6_GEj5jObMHprNmJ7rQQjhFhl4tsriuclUzdiU1-82gFiKaKmJ3HmOiJ-wW8dlXAgSgc03-r_FYDlutd62Ft1fAV6KUd-QKgxE3fNQDu0UUd6LhHjRxHenWbQi9VUZvqDVep8wimJG-lvs87iBYTJLz54hWJuyV_BeGN0WMBIGAyZOeukzBq1eVqNFZzYFA32egdXxyKDBS08myUmPRizqUN8yMirZI8Oo7-cG50w29rQGS6qPPH7M4B25M2tGU8FJ44ToW7CAAAxggLxMIIC7QIBATCBiTB1MQswCQYDVQQGEwJERTElMCMGA1UEChMcVC1TeXN0ZW1zIEludGVybmF0aW9uYWwgR21iSDEfMB0GA1UECxMWVC1TeXN0ZW1zIFRydXN0IENlbnRlcjEeMBwGA1UEAxMVVGVsZVNlYyBCdXNpbmVzcyBDQSAxAhAnhZHNNRS6MPClsEXD_dkBMA0GCWCGSAFlAwQCAQUAoIIBBDAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yMTA5MDMwNDI3MDlaMC8GCSqGSIb3DQEJBDEiBCCgWn8ecu2OkgGYQh0gwttX32_iwoYKHf5H6_owkr2TDDA2BgkqhkiG9w0BCQ8xKTAnMAsGCWCGSAFlAwQBAjALBglghkgBZQMEARYwCwYJYIZIAWUDBAEqMGEGCSqGSIb3DQEJNDFUMFIwDQYJYIZIAWUDBAIBBQChQQYJKoZIhvcNAQEKMDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEFAKIDAgEgMEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIASCAQA6IdPhvzdHoBnQaKkXcKGRt-tGCzwxNDlfwo4-uBBIKHyij_NRjbDYvUnAGYjG6infUDgdT7SBHrzMFTDYZVwL50DjkIrzfauJw5LUeNJFjr68nz_beUG5aITF19z_puhsHYXvXRjJyL-tFwFNbeZY4fsWdwwxQbs_7apP1DJiJe_qya3cXq4oZA_gZ7AHw_lvYmjUfoC53qL0FEd5Bsq7meQTXk5GM0pnAqqGpkIFpmn90dpetK_Entc3XBTVCG0W5whuzTRscM2mTKahMA9TRtgfFybnADRVz7LcBZDukEXuDkrigOvh7AdLdYxmChoeDpEB8uzKF5EopOMCvwplAAAAAAAA) and [after](https://lapo.it/asn1js/#MIITiwYJKoZIhvcNAQcCoIITfDCCE3gCAQExDzANBglghkgBZQMEAgEFADALBgkqhkiG9w0BBwGgghCGMIIDwzCCAqugAwIBAgIBATANBgkqhkiG9w0BAQsFADCBgjELMAkGA1UEBhMCREUxKzApBgNVBAoMIlQtU3lzdGVtcyBFbnRlcnByaXNlIFNlcnZpY2VzIEdtYkgxHzAdBgNVBAsMFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxJTAjBgNVBAMMHFQtVGVsZVNlYyBHbG9iYWxSb290IENsYXNzIDIwHhcNMDgxMDAxMTA0MDE0WhcNMzMxMDAxMjM1OTU5WjCBgjELMAkGA1UEBhMCREUxKzApBgNVBAoMIlQtU3lzdGVtcyBFbnRlcnByaXNlIFNlcnZpY2VzIEdtYkgxHzAdBgNVBAsMFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxJTAjBgNVBAMMHFQtVGVsZVNlYyBHbG9iYWxSb290IENsYXNzIDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCqX9obX+hzkeXaXPSi5kfl82hVYAUdAqSzm1nzHoqvNK38DcLZSBnuaY/JIPwhqgcZ7bBcrGXHX+0CfHt8LRvWurmAwhiCFoT6ZrAIxlQjgeTNuUk/9k9uN0goOA/FvudocP05l03Sx5iRUKrERLMjfTlH6VJi1hKTXrcxlkIF+3anHqP1wvzpesVsqXFP6st4vGCvx9702cu+fjOlbpSD8DT6IavqjnKgP6TeMFvvhk1qlVtDRKgQFRzlAVfFmPHmBiiRqiDFt1MmUUOyCxGVWOHAD3bZwI18gfNycJ5v/hqO2V81xrJvNHy+SE/iWjnX2J14np+GPgNeGYtEotXHAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBS/WSA2AHmgoCJrjNXyYdK4LMuCSjANBgkqhkiG9w0BAQsFAAOCAQEAMQOiYQsfdOhyNsZt+U2e+iKo4YFWz827n+qrkRk4r6p8FU3ztqONpfSO9kSpp+ghla0+AGIWiPACuvxhI+YzmzB6azZie60EI4RYZeLbK4rnJVM3YlNfvNoBYimipidx5joifsFvHZVwIEoHNN/q/xWA5brXethbdXwFeilHfkCoMRN3zUA7tFFHei4R40cR3p1m0IvVVGb6g1XqfMIpiRvpb7PO4gWEyS8+eIVibslfwXhjdFjASBgMmTnrpMwatXlajRWc2BQN9noHV8cigwUtPJslJj0Ys6lDfMjIq2SPDqO/nBudMNva0Bkuqjzx+zOAduTNrRlPBSeOE6FuwjCCBXAwggRYoAMCAQICBkiNAl3W9DANBgkqhkiG9w0BAQsFADCBgjELMAkGA1UEBhMCREUxKzApBgNVBAoMIlQtU3lzdGVtcyBFbnRlcnByaXNlIFNlcnZpY2VzIEdtYkgxHzAdBgNVBAsMFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxJTAjBgNVBAMMHFQtVGVsZVNlYyBHbG9iYWxSb290IENsYXNzIDIwHhcNMTIxMTI5MTEyMzU1WhcNMjQxMTI5MjM1OTU5WjB1MQswCQYDVQQGEwJERTElMCMGA1UEChMcVC1TeXN0ZW1zIEludGVybmF0aW9uYWwgR21iSDEfMB0GA1UECxMWVC1TeXN0ZW1zIFRydXN0IENlbnRlcjEeMBwGA1UEAxMVVGVsZVNlYyBCdXNpbmVzcyBDQSAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0TDUTUTD5EtatBieDlEntaliSXoaBsBzLBGJVZKsDsv+SC+7XeP0qYi6gWvk+zcdLFfrRZhVQUaJx+enMWR7nngIn8AYP+lKYrGE/ODQzK2VLruAavWnZMU3+94956DNsaJ0NaPP7+1NdG26jSQatJ/8WlVGO//3wvF5enZ3z0/ryiKNdtgFmfcE8TyffNuoafBV36NBqElLbl0gcQ26iwluayLwpJ3zVonA1sBYMAhX5mLdjj/QveO6OFdfrdI1Ururrsa2nyESk69Fi1Y21cykTDYvM+G0guZkRV3u6tfcoE1Bf95mmYr9XW7sRet04gkT9orqqGcoak6f+BKstQIDAQABo4IB9jCCAfIwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBSGiJMfi+tVlmXVRwG9N4x8zajHozAfBgNVHSMEGDAWgBS/WSA2AHmgoCJrjNXyYdK4LMuCSjASBgNVHRMBAf8ECDAGAQH/AgEAMFMGA1UdIARMMEowPgYJKwYBBAG9Rw0ZMDEwLwYIKwYBBQUHAgEWI2h0dHA6Ly9zYmNhLnRlbGVzZWMuZGUvY3BzL2NwczIucGRmMAgGBmeBDAECAjCB+gYDVR0fBIHyMIHvMDqgOKA2hjRodHRwOi8vY3JsLnNiY2EudGVsZXNlYy5kZS9ybC9HbG9iYWxSb290X0NsYXNzXzIuY3JsMIGwoIGtoIGqhoGnbGRhcDovL2xkYXAuc2JjYS50ZWxlc2VjLmRlL0NOPVQtVGVsZVNlYyUyMEdsb2JhbFJvb3QlMjBDbGFzcyUyMDIsT1U9VC1TeXN0ZW1zJTIwVHJ1c3QlMjBDZW50ZXIsTz1ULVN5c3RlbXMlMjBFbnRlcnByaXNlJTIwU2VydmljZXMlMjBHbWJILEM9REU/QXV0aG9yaXR5UmV2b2NhdGlvbkxpc3QwOgYIKwYBBQUHAQEELjAsMCoGCCsGAQUFBzABhh5odHRwOi8vb2NzcDA0LnRlbGVzZWMuZGUvb2NzcHIwDQYJKoZIhvcNAQELBQADggEBAJOF0euEehlZyCWAOiSluZZxBpv+1g504EDd1c1dHSCAGUNJD3h23iPeXMw37aPKfEohBNklkZmxPweyZELcFOelj9PtrSBteR1SLBeyktCzXzAvRD5W7zRXtoeQqbxHdYgykz7vaUsaSjANsecNQwFlh3w3j5tK1atRyfb1l8MeP14UlK62DXJZ/OXXF1/E4mZO2maNKNEK1zu2LFqiTtbY75KVLWWZJGgwioINYs7fh//8OPWEes7HjHFGeiMpfaz2VigCrICLr1egSB2IYZ9KPv/fvKFmnRoBhvMcEVXLWtL8MLkU1isJB+xq4/aNURpEKUdul47BMdY1CPgeJE8wggdHMIIF+6ADAgECAhAnhZHNNRS6MPClsEXD/dkBMEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIDB1MQswCQYDVQQGEwJERTElMCMGA1UEChMcVC1TeXN0ZW1zIEludGVybmF0aW9uYWwgR21iSDEfMB0GA1UECxMWVC1TeXN0ZW1zIFRydXN0IENlbnRlcjEeMBwGA1UEAxMVVGVsZVNlYyBCdXNpbmVzcyBDQSAxMB4XDTIwMDIwNzEzMzQwOVoXDTIzMDIwNzIzNTk1OVowgcgxCzAJBgNVBAYTAkRFMRUwEwYDVQQKEwxBbXByaW9uIEdtYkgxFzAVBgNVBAsTDnYzLmFtcHJpb24ubmV0MRkwFwYDVQQLDBBSU0FTU0EtUFNTX1NNSU1FMRswGQYDVQQDExJHUlA6U3J2RXhjTmV3YXNJSVAxGzAZBgNVBAQTEkdSUDpTcnZFeGNOZXdhc0lJUDEhMB8GCSqGSIb3DQEJARYSZWRpLmJtQGFtcHJpb24ubmV0MREwDwYDVQQFEwgyMDIwMDIwNzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJbCJrLTw3dzYSIXy05FsDPrzPdCHVLDXZEDQkX2S3qlAqmnEVIv1mZ+6yhB3L0uc+OvKLxXbTbUK3JJ/qn/nkVmLmiGH7JlYleLNxCnvTh/lEb1SqYq+DklG6TkvzWY7pKWNKuOgwwQvUR7RJXP4e/BKFLS9BUmTLk7bf7tGlhvosK88zRpBQ7Ridw+xgtg4D1zdBsraON7Tatc8+QP1RNzw4N+NVzm0Bia5WDV1Gfn0i6teoNObPG6XoZtf9Rg/aoiITNHNJo5ZEhOFspTdLGJnP5Mcio4wrcYfro8Oi9uNwNqL78RAqdDF91IMHhK0CXhTniaiysouPBdVTRlOrcCAwEAAaOCAxUwggMRMB8GA1UdIwQYMBaAFIaIkx+L61WWZdVHAb03jHzNqMejMB0GA1UdDgQWBBRA3Cx2Ygfd4+fUInS0BvG/WpjeujAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMFgGA1UdIARRME8wQwYJKwYBBAG9Rw0ZMDYwNAYIKwYBBQUHAgEWKGh0dHA6Ly9zYmNhLnRlbGVzZWMuZGUvZG93bmxvYWQvY3BzMi5wZGYwCAYGBACPegEBMAkGA1UdEwQCMAAwgfAGA1UdHwSB6DCB5TA9oDugOYY3aHR0cDovL2NybC5zYmNhLnRlbGVzZWMuZGUvcmwvVGVsZVNlY19CdXNpbmVzc19DQV8xLmNybDCBo6CBoKCBnYaBmmxkYXA6Ly9sZGFwLnNiY2EudGVsZXNlYy5kZS9DTj1UZWxlU2VjJTIwQnVzaW5lc3MlMjBDQSUyMDEsT1U9VC1TeXN0ZW1zJTIwVHJ1c3QlMjBDZW50ZXIsTz1ULVN5c3RlbXMlMjBJbnRlcm5hdGlvbmFsJTIwR21iSCxDPURFP0NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3QwggEnBggrBgEFBQcBAQSCARkwggEVMC8GCCsGAQUFBzABhiNodHRwOi8vb2NzcDAzLnNiY2EudGVsZXNlYy5kZS9vY3NwcjBEBggrBgEFBQcwAoY4aHR0cDovL2NydC5zYmNhLnRlbGVzZWMuZGUvY3J0L1RlbGVTZWNfQnVzaW5lc3NfQ0FfMS5jcnQwgZsGCCsGAQUFBzAChoGObGRhcDovL2xkYXAuc2JjYS50ZWxlc2VjLmRlL2NuPVRlbGVTZWMlMjBCdXNpbmVzcyUyMENBJTIwMSxvdT1ULVN5c3RlbXMlMjBUcnVzdCUyMENlbnRlcixvPVQtU3lzdGVtcyUyMEludGVybmF0aW9uYWwlMjBHbWJILGM9ZGU/Y0FDZXJ0aWZpY2F0ZTAdBgNVHREEFjAUgRJlZGkuYm1AYW1wcmlvbi5uZXQwQQYJKoZIhvcNAQEKMDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEFAKIDAgEgA4IBAQCOV/x34yoRtcN+kv1xkdn3bstc4GH+njwK0bsiEk3O0eQCv//uj7CeTu5lEahGmh3o4N0MO+82HvKyig74CUTL7Rdh2Mmlt/yoSx/1iv5DKHjZeyLRhUu1GsJ/9rMgaY59qHJx62XMKJOa5+yzV4PTHuZp1yQ1c1SDmQMYaQVjpr0uk39NduGvmRwwMouhAGaTFwb9R8gvdnNNPOjd/bnrCtxccu8AaxNx5nrVzv3e6UtNkfQ8oPNBuW9TyIW0Dk8248keeOkym1a0rYxO7/iGopV/QgD15+3O3OBL0rBXwJbjMbt4ILis/ZIBILdx7J+WGrxJvhHyLR8oJu0NMtOyMYICyTCCAsUCAQEwgYkwdTELMAkGA1UEBhMCREUxJTAjBgNVBAoTHFQtU3lzdGVtcyBJbnRlcm5hdGlvbmFsIEdtYkgxHzAdBgNVBAsTFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxHjAcBgNVBAMTFVRlbGVTZWMgQnVzaW5lc3MgQ0EgMQIQJ4WRzTUUujDwpbBFw/3ZATANBglghkgBZQMEAgEFAKCB3TAPBgkqhkiG9w0BCQ8xAjAAMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIxMDkwMzA0MjcwOVowLwYJKoZIhvcNAQkEMSIEIKBafx5y7Y6SAZhCHSDC21ffb+LChgod/kfr+jCSvZMMMGEGCSqGSIb3DQEJNDFUMFIwDQYJYIZIAWUDBAIBBQChQQYJKoZIhvcNAQEKMDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEFAKIDAgEgMEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIASCAQA6IdPhvzdHoBnQaKkXcKGRt+tGCzwxNDlfwo4+uBBIKHyij/NRjbDYvUnAGYjG6infUDgdT7SBHrzMFTDYZVwL50DjkIrzfauJw5LUeNJFjr68nz/beUG5aITF19z/puhsHYXvXRjJyL+tFwFNbeZY4fsWdwwxQbs/7apP1DJiJe/qya3cXq4oZA/gZ7AHw/lvYmjUfoC53qL0FEd5Bsq7meQTXk5GM0pnAqqGpkIFpmn90dpetK/Entc3XBTVCG0W5whuzTRscM2mTKahMA9TRtgfFybnADRVz7LcBZDukEXuDkrigOvh7AdLdYxmChoeDpEB8uzKF5EopOMCvwpl) being parsed by asn1crypto (look for the *sMIMECapabilities* field and see how it was 1) moved, 2) emptied).

This pull request adds support for rfc2633 sMIME capabilities signed attr, to allow parsing it as a set of sequences of algorithm identifiers (as per the spec). This prevents the faulty parsing and dumping behaviour, only for this signed attr.

I need to add a couple of unit tests, could you provide guidance about this? I think new fixtures need to be generated for the CMS tests, but I'm not sure what's the most appropriate way.

Thank you for this incredibly useful library.

### CODE REVIEW

**Comment by wbond** [comment]
I fixed the bug you identified in 5a24aed1b99e7f51ba38183aebbcce86e6eb4d23. It was that if you try and force DER re-encoding of a Sequence that has no info, it resulted in an empty value since it didn't known the canonical encoding.

Now if it hits such a situation, it preserves the existing encoding.

**Comment by wbond** [comment]
In terms of tests, ideally you can just add a fixture with a value encoded by another program and ensure asn1crypto can parse it.

**Comment by Hellzed** [comment]
I've added a sMIME capabilities parsing test on a PKCS#7 signature generated by Thunderbird 91.5.0.

I have also updated the `cms` module to better reflect sMIME capabilities semantics as per rfc2633: 
 - not all capability OIDs are `AlgorithmId`s (some are compression or encoding-related), and even when a capability OID is identical to an `AlgorithmId`, the associated `params` field may not be structured in the same way as expected by a full `AlgorithmIdentifier` (e.g.: RC2 capability `params` value is only the key length, not `Rc2Params`). This requires a new, different class `cms.SMIMECapabilityIdentifier` without the checks enforced by `algos.AnyAlgorithmIdentifier`.
 - the sMIME capabilities attribute value is a SET OF containing a single instance of a sequence (the capabilities themselves). This is apparent in the test.

A nice extra would have been to provide the algorithm name as `capability_id` attribute (when using `SMIMECapabilityIdentifier.native`) if the OID matches a known algorithm, but this doesn't seem actually useful for now.

**Comment by wbond** [comment]
This looks good - thanks! I have a commit to add the algorithm names, but for some reason GitHub isn't letting me push to your master branch even though the PR says I can. I'll add it after I merge.

**Comment by wbond** [comment]
You can see my tweaks at 4791c1edac3dda76d9a718f2a35347f10ba35028

**Comment by Hellzed** [comment]
Awesome, thank you!

**Pull request merged**
