### PR TITLE
Fixed some incorrectly computed EC private key sizes.

### PR DESCRIPTION
**Pull request by joernheissler**
Private key is an integer from interval [1, curve_order). The curve
order is denoted by n in SECG or q in some RFCs.
The byte length is therefore ceil(log2(n) / 8).

Double checked by comparing to what openssl generates:

```python
def size(curve: str) -> Tuple[str, int]:
    key = PrivateKeyInfo.load(
        unarmor(
            check_output(["openssl", "genpkey", "-algorithm", "ec", "-pkeyopt", "ec_paramgen_curve:" + curve])
        )[2]
    )
    oid = key["private_key_algorithm"]["parameters"].chosen.dotted
    priv_len = len(key["private_key"].parsed["private_key"].contents)
    return oid, priv_len
```

### CODE REVIEW

**Comment by wbond** [comment]
For the first one, sect239k1, I must have made a transcription error. However, for the second one, I am getting a different result:

 - sect239k1
   - Order: 2000 00000000 00000000 00000000 005a79fe c67cb6e9 1f1c1da8 00e478a5
   - Python: `math.ceil(math.log2(int('2000000000000000000000000000005a79fec67cb6e91f1c1da800e478a5', 16)) / 8)`
   - Result: 30
 - sect113r1
   - Order: 010000 00000000 00d9ccec 8a39e56f
   - Python: `math.ceil(math.log2(int('0100000000000000d9ccec8a39e56f', 16)) / 8)`
   - Result: 14

**Comment by joernheissler** [comment]
log2(0x0100000000000000d9ccec8a39e56f) is about 112.00000000000000002, but python computes exactly 112.0. If you use bit_length() instead of log2, you'll get 113. Perhaps I shouldn't have used ceil+log2 in the commit message :(

**Comment by wbond** [comment]
Good old floating point imprecision!

**Comment by wbond** [comment]
This will have to be rebased on `master` to get the CI to pass

**Comment by wbond** [comment]
Thanks for spotting this and getting it fixed!

**Pull request merged**
