### PR TITLE
Add SCEP attribute type mappings, 2nd try

### PR DESCRIPTION
**Pull request by laurivosandi**
Hi, I hope this is suitable for merging

### CODE REVIEW

**Comment by wbond** [comment]
Looks like there are some lint errors to fix here.

**Comment by laurivosandi** [comment]
Hi, not sure what's failing now :/

**Comment by laurivosandi** [comment]
Bump!

**Comment by wbond** [comment]
Sorry for the delay on this. I see version 08 adds fail info text of some sort. Should that be added to this PR? https://tools.ietf.org/html/draft-gutmann-scep-08#section-3.2.1

**Comment by wbond** [comment]
@laurivosandi Ping

**Comment by wbond** [comment]
Checking in again @laurivosandi

**Comment by wiml** [comment]
The recent drafts add a definition for a `failInfoText` attribute, but do not assign an OID arc for it (the `id-scep` base is just defined as `{id-pkix TBD1}` which I take to mean "to be determined" in some future draft; see the editor's note in section 7.

**Pull request closed without merging**
