### PR TITLE
Drop support for EOL Python 2.6, 3.2, and 3.3

### PR DESCRIPTION
**Pull request by jdufresne**
Python 2.6, 3.2, and 3.3 are end of life. They are no longer receiving bug fixes, including for security issues. These Pythons went EOL on the following dates:

Python 2.6: 2013-10-29
Python 3.2: 2016-02-20
Python 3.3: 2017-09-29

For additional details on support Python versions, see:

Removing support for EOL Pythons will reduce testing and maintenance resources. Allows removing workarounds in code.

Using [pypinfo](https://github.com/ofek/pypinfo), here are the download statistics for the last 30 days:

```
$ pypinfo --percent asn1crypto pyversion
```

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 2.7            |  68.43% |      1,431,192 |
| 3.6            |  21.18% |        442,934 |
| 3.5            |   6.38% |        133,479 |
| 3.4            |   3.47% |         72,648 |
| 2.6            |   0.31% |          6,500 |
| 3.7            |   0.22% |          4,669 |
| 3.3            |   0.01% |            108 |
| None           |   0.00% |             10 |
| 3.8            |   0.00% |              9 |
| 3.2            |   0.00% |              1 |

### CODE REVIEW

**Comment by joernheissler** [comment]
It looks like other packages (e.g. oscrypto) depend on `util.OrderedDict`.
Might be better to keep an import until those other packages are updated.

And really hurts to see that almost everyone is still using py2.7. Are those stats correct?

**Comment by wbond** [comment]
This package was partially developed for Sublime Text 2 and 3 which run on 2.6 and 3.3, so I won’t be dropping them for a while.

**Comment by wbond** [comment]
Also, the ST2 and ST3 numbers are not reflected in pypi.

**Comment by jdufresne** [comment]
I'm not very familiar with the inner workings of Sublime Text. Is the Python version bundled and unable to be upgraded?

**Comment by wbond** [comment]
Yes, that is correct. Sublime Text 2 is hard-coded to Python 2.6 (there are some minor details, such as it using the system 2.6 on OS X) and Sublime Text 3 has a custom build of Python 3.3 that is fully self-contained, and contains various patches we've had to apply to work around issues.

We may be adding a new environment at some point during the Sublime Text 3.x lifecycle, but there are thousands of plugins written for Sublime Text 3, and many of the popular packages have shared libraries or compiled `.pyc` files that would break if the minor version was bumped.

Sublime Text 2 is EOL, but Package Control still supports it for now. At some point the PC codebase will drop support for ST2, in which case it would be viable for asn1crypto and oscrypto to also.

Since Sublime Text 3 was released less than a year ago, this project will be supporting Python 3.3 for a long time (easily another 3+ years).

**Comment by hugovk** [comment]
> Sublime Text 2 is EOL, but Package Control still supports it for now. At some point the PC codebase will drop support for ST2, in which case it would be viable for asn1crypto and oscrypto to also.

Here's a link to the Package Control issue about the next 4.0.0 release, which will be only support ST3.

https://github.com/wbond/package_control/issues/1310

**Pull request closed without merging**
