### PR TITLE
Add more signature algorithm entries from NIST CSOR (mainly related to SHA-3)

### PR DESCRIPTION
**Pull request by MatthiasValvekens**
- Add OIDs for SHA-3 family digest functions for use with DSA and RSA with PKCS#1 v1.5 padding, updating `signature_algo` and `hash_algo` accordingly.
 - Complete the list of OIDs for DSA with SHA-2 digests.
 - Add missing entries for ECDSA with SHA-3 to the `hash_algo` property lookup table.

FWIW, this PR was triggered by the recent publication of [this standard](https://www.iso.org/standard/45874.html), which adds SHA-3 support to PDF. I thought `asn1crypto` already included the relevant OIDs, but apparently only for ECDSA.

### CODE REVIEW

**Comment by MatthiasValvekens** [comment]
FWIW, tests are failing because one of the certs in the `certvalidator` test suite expired... I'll see if I can easily do something about that.


(I use `freezegun` in my own certificate-related tests to avoid running into this issue, but I'm not sure if that library supports Python versions going back as far as 2.6)

**Comment by MatthiasValvekens** [comment]
I made a PR against `certvalidator` to update the failing revocation tests.

**Comment by MatthiasValvekens** [comment]
OK, the issue in `certvalidator` was resolved in the meantime, but now it appears that the test I added is failing because `subTest` doesn't exist in Python 3.3 and under.

Before I fix the PR itself, I'll annoy you with this question once more: are you still not willing to reconsider your position on supporting old Python versions? ;)  Python 3.3 has been EOL for over 5 years at this point. And does `package_control` still require Python 2 support?

**Comment by wbond** [comment]
I still maintain some commercial software for Sublime Text, and in less than 12 hours of publishing an update, I had bug reports from users running Sublime Text 2. Since it really isn't that much overhead for me to keep supporting Python 2 at this point, I probably will.

I am happy to deal with the overhead of those bits - for instance, I had no problem refactoring this to not use subTest, and instead use the existing parameterized tests functionality.

**Comment by wbond** [comment]
I've made some tweaks here and am just waiting for the CI results

**Pull request merged**
