### PR TITLE
Add RFC 8410 OIDs

### PR DESCRIPTION
**Pull request by nickray**
Would like to use Ed25519 in python-pkcs11, which uses this library.
Let me know if additional changes need to be made, besides the constants.

### CODE REVIEW

**Comment by nickray** [comment]
Looks like some server certificate expired :)

**Comment by wbond** [comment]
These OIDs are used to identify public keys, signatures and private keys. Thus they will need to be added to:

 - https://github.com/wbond/asn1crypto/blob/e5779a46c01be83244dfd5f3e9be17dd006dc754/asn1crypto/keys.py#L456
 - https://github.com/wbond/asn1crypto/blob/e5779a46c01be83244dfd5f3e9be17dd006dc754/asn1crypto/keys.py#L926

The EdDSA OIDs should be added to:

 - https://github.com/wbond/asn1crypto/blob/e5779a46c01be83244dfd5f3e9be17dd006dc754/asn1crypto/algos.py#L232
 - https://github.com/wbond/asn1crypto/blob/e5779a46c01be83244dfd5f3e9be17dd006dc754/asn1crypto/algos.py#L304

The ECDH OIDs should be added to:

 - https://github.com/wbond/asn1crypto/blob/e5779a46c01be83244dfd5f3e9be17dd006dc754/asn1crypto/algos.py#L435

https://github.com/wbond/asn1crypto/blob/e5779a46c01be83244dfd5f3e9be17dd006dc754/asn1crypto/keys.py#L493 will need to be added to treat the keys and signatures as strictly opaque byte strings (from reading the RFC). There will be some other places such as https://github.com/wbond/asn1crypto/blob/e5779a46c01be83244dfd5f3e9be17dd006dc754/asn1crypto/keys.py#L977.

Ideally we really need an example certificate using EdDSA to make sure this appears to be working.

**Comment by wbond** [comment]
To add another component to getting this merged, we'll need some keys and certs using these algorithms to ensure we are parsing properly. We'll add them as fixtures to the test suite.

It looks like with OpenSSL command line we can generate a private key using something like:

```bash
openssl genpkey -algorithm ed25519 -out ed25519.pkey
```

https://www.openssl.org/docs/manmaster/man1/genpkey.html has some info.

**Comment by nickray** [comment]
From my side, thanks a lot for gathering the requirements. However, I will not have the time to dig into this in the near future, so if someone else wants to take it, please go ahead.

**Comment by joernheissler** [comment]
I'll open a new PR in a few days. openssl now supports these so it's easy to create keys and test.

```
$ for algo in x25519 ed25519 x448 ed448; do openssl genpkey -algorithm $algo | openssl pkey -pubout -outform der | dumpasn1 -; done
  0  42: SEQUENCE {
  2   5:   SEQUENCE {
  4   3:     OBJECT IDENTIFIER curveX25519 (1 3 101 110)
       :     }
  9  33:   BIT STRING
       :     0A 41 69 F5 21 8C EC FF 7D 18 60 0A AB E2 ED B6
       :     06 88 00 F3 6A DD 3B 44 86 5F 05 DB 73 64 32 6A
       :   }

  0  42: SEQUENCE {
  2   5:   SEQUENCE {
  4   3:     OBJECT IDENTIFIER curveEd25519 (1 3 101 112)
       :     }
  9  33:   BIT STRING
       :     3D C9 E4 58 B0 D9 0D C7 FB CA 81 38 28 D2 F1 41
       :     19 C7 7D 7A 14 68 9F CF A0 F5 15 E2 6D 87 50 0D
       :   }

  0  66: SEQUENCE {
  2   5:   SEQUENCE {
  4   3:     OBJECT IDENTIFIER curveX448 (1 3 101 111)
       :     }
  9  57:   BIT STRING
       :     0C 41 AD EE EA 8D F1 AB 12 A8 37 36 04 D2 FD 66
       :     B2 44 B0 29 11 A6 1B E7 6B 99 2B D5 67 38 F4 1D
       :     05 00 47 88 65 FF 85 34 89 1E C5 BE 83 52 3E B5
       :     15 C7 9F BE 9D D5 B1 34
       :   }

  0  67: SEQUENCE {
  2   5:   SEQUENCE {
  4   3:     OBJECT IDENTIFIER curveEd448 (1 3 101 113)
       :     }
  9  58:   BIT STRING
       :     03 43 B6 7D D6 6E A3 A1 AE C7 F2 14 0F CD D5 A6
       :     65 7C 4D E6 AA 27 C9 B2 2A 53 30 0E D9 9F B7 1C
       :     4E 47 1B 70 A5 3C 7A 58 A4 BB A1 F6 8F 44 01 17
       :     D1 40 36 EC D6 6D 64 12 80
       :   }
```

**Pull request closed without merging**
