### PR TITLE
Add pkcs12_sha1_rc4_128 to EncryptionAlgorithmId

### PR DESCRIPTION
**Pull request by luckylud**
I use asn1crypto for one project and I need to add this key (1.2.840.113549.3.4) as pkcs12_sha1_rc4_128 usefull for rc4

Thanks

### CODE REVIEW

**Comment by wbond** [comment]
Can you provide a source for this OID such as an RFC?

**Comment by joernheissler** [comment]
Best/Oldest I could find is http://www.umich.edu/~x509/ssleay/asn1-oids.html
I emailed RSA, but I doubt that I'll even get an answer.

**Comment by joernheissler** [comment]
@luckylud Why did you name this `pkcs12_sha1_rc4_128` instead of `rc4`?

**Comment by luckylud** [comment]
@joernheissler  that was my need for this OID, to get algos.EncryptionAlgorithmId('pkcs12_sha1_rc4_128')

@wbond : 
Test failed because pkcs12_sha1_rc4_128 is already define as:
'1.2.840.113549.1.12.1.1': 'pkcs12_sha1_rc4_128',

So catch it with _dotted value :)

Many thanks for your powerfull library :+1:

**Comment by wbond** [comment]
Based on the OpenSSL codebase, this OID is "rc4" - https://github.com/openssl/openssl/blob/97ace46e11dba4c4c2b7cb67140b6ec152cfaaf4/crypto/objects/objects.txt#L406.

As you've seen, pkcs12_sha1_rc4_128 is 1.2.840.113549.1.12.1.1, which openssl confirms at https://github.com/openssl/openssl/blob/97ace46e11dba4c4c2b7cb67140b6ec152cfaaf4/crypto/objects/objects.txt#L355.

**Comment by wbond** [comment]
I've added this OID with the name `rc4` in 6a7dba8b6b775233d4f66e6c5bed3cfc5a47abd6.

**Pull request closed without merging**
