### PR TITLE
Fix/0086 generalized time

### PR DESCRIPTION
**Pull request by erny**
Make parsing GeneralizedTime more flexible

### CODE REVIEW

**Comment by wbond** [comment]
Can you rebase on top of master to get CircleCI working properly again?

**Comment by erny** [comment]
Hmmm, I'm not a git profi right now. How do I do that?

Ernesto Revilla
Área Técnica
TangramBPM.es
Tlf: 630 244 136



2018-04-05 13:38 GMT+02:00 Will Bond <notifications@github.com>:

**Comment by wbond** [comment]
Do you use the command line? If so, `git pull --rebase master` should do it.

**Comment by wbond** [comment]
That it assuming that your fork's master is up to date with wbond/asn1crypto.

**Comment by wbond** [comment]
If you have trouble, it looks like I can probably push to your fork

**Comment by wbond** [comment]
Could you try rebasing on master again? I think I finally got the CI tasks working again after the recent PyPI changes.

**Comment by erny** [comment]
Hi, I had problems rebasing but did a merge from master. The change is trivial, so it shouldn't give any other problems. Regards.

**Comment by erny** [comment]
Why does this give an error on codecov/patch ?

**Comment by erny** [comment]
Any news here?

**Pull request closed without merging**
