### PR TITLE
Add support for CMS Attribute Protection RFC6211

### PR DESCRIPTION
**Pull request by aalba6675**
Add another CMS attribute from RFC6211

### CODE REVIEW

**Comment by aalba6675** [comment]
Tests pass on Fedora 25 with CPy 3.5.3/2.7.13 on command line.
Seems to be a lot of CI failures when submitting code coverage.

**Comment by wbond** [comment]
No, you have some flake8 failures. Try running:

```bash
python run.py lint
```

**Comment by aalba6675** [comment]
I missed the linting, thanks. There remains a failed check KeyboardInterrupt in appveyor which seems unrelated.

**Comment by aalba6675** [comment]
I will squash the two commits and resubmit.

**Pull request closed without merging**
